dist: xenial

language: cpp

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libgflags-dev

matrix:
  include:
    - compiler: clang
      env: BUILD_TYPE="Debug"
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: SANITIZER="ASAN"
    - compiler: clang
      env: SANITIZER="TSAN"
    - compiler: clang
      env: SANITIZER="UBSAN"
    - env: COMPILER=gcc8

install:
  - git clone --depth=1 --branch=tikv-3.0 https://github.com/pingcap/rocksdb.git 
  - if [ "${COMPILER}" == gcc8 ]; then
      CC=gcc-8 && CXX=g++-8;
    fi
  - if [ ! -z "${BUILD_TYPE}" ]; then
      BUILD_OPT="-DCMAKE_BUILD_TYPE=${BUILD_TYPE}";
    fi
  - if [ ! -z "${SANITIZER}" ]; then
      SANITIZER_OPT="-DWITH_${SANITIZER}=ON" && TOOLS_OPT="-DWITH_TITAN_TOOLS=OFF";
    fi

script:
  - ${CXX} --version
  - echo $BUILD_OPT
  - echo $SANITIZER_OPT
  - echo $TOOLS_OPT
  - cmake . -DROCKSDB_DIR=./rocksdb -DTRAVIS=ON ${BUILD_OPT} ${SANITIZER_OPT} ${TOOLS_OPT} && make -j4 && ctest -R titan
